apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  triggers:
  - type: ImageChange
    imageChangeParams:
      automatic: false
      containerNames:
      - {{ .Chart.Name }}
      from:
        kind: ImageStreamTag
        name: "{{ include "helm.fullname" . }}:latest"
  selector:
    {{- include "helm.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          ports:
            - containerPort: {{ .Values.service.port }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
