apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's http port.
  labels:
    app: {{ .Values.application_name }}-web
    template: basic-dotnet-core
  name: {{ .Values.application_name }}-web
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    deploymentConfig: {{ .Values.application_name }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's http port.
  labels:
    app: {{ .Values.application_name }}-ui
    template: basic-dotnet-core
  name: {{ .Values.application_name }}-ui
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    deploymentConfig: {{ .Values.application_name }}-ui
