kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "dotnet-build"
spec:
  strategy:
    type: "Source"
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "dotnet:3.1"
      runtimeImage: 
        kind: "ImageStreamTag"
        name: "dotnet-runtime:3.1"
  output:
    to:
        kind: "ImageStreamTag"
        name: "s2i-dotnetcore-ex:latest"